name: Test PHP
on:
  push:
    branches-ignore:
      - staging
      - production
    paths:
      - '**.php'
      - '**.yml'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer
          extensions: sqlite
      - uses: actions/checkout@v2
      - name: Installing Dependencies
        run: composer i
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: ./vendor/bin/phpunit -c tests/php/phpunit.xml --colors=always --testdox
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

